---
title: "workshop-09"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(lterdatasampler)
library(ggeffects)
library(here)

data(pie_crab)

```

```{r}
ggplot(aes(x = latitude, y = size), data = pie_crab)+ #create plot
  geom_point(color = "orange")+ # scatter plot
  labs(x = "Latitude", y = "Size")+ # update axis labels
  theme_minimal() # remove gridlines
```

```{r}
crab_model <- lm(size ~ latitude, data = pie_crab)
par(mfrow = c(2,2))
    plot(crab_model)
    
    
```

```{r}
summary(crab_model)
```

Summarize results:

slope: 0.49

y intercept: -3.6 +/- 1.27

For each 1 degree increase in latitude, we expect to see a 0.49 +/- 0.034 mm increase in crab size.

Model stats: f(1, 390) = 208.5, p \< 0.001, alpha = 0.05, R^2^ = 0.35

general notes about collaboration:

1.  always save your changes! always commit and push your changes

```{=html}
<!-- -->
```
2.  comment your code so people know what you're doing
3.  TALK TO YOUR COLLABORATORS!!!!!
4.  ALWAYS PULL BEFORE YOU START WORKING IN CODE !!!!!!
